repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all --
        language: system
        types: [file]
        files: \.rs$
        pass_filenames: false
      - id: cargo-check
        name: cargo check
        entry: cargo check -q
        language: system
        types: [file]
        files: \.rs$
        pass_filenames: false
